mortgage cal html and knexfile
lishure/Project2 pull request #7
Opened 2019-06-07 03:11 UTC by cuongle30

2019-06-07 03:16 UTC, drukelly-zz requested changes
Knexfile looks good! I wonder if we should create a branch for tests? What I mean is when we're trying to prototype something that's not going to be included in the project, we can put it in a folder called **tests**? This folder can live on the root folder of our project. That way, we can keep our project clean. What do y'all think?

2019-06-07 03:26 UTC, cuongle30 reviewed
okay

2019-06-07 03:37 UTC, lishure approved these changes

2019-06-08 17:44 UTC, drukelly-zz approved these changes

2019-06-08 17:45 UTC, closed without merging

2019-06-08 17:46 UTC, cuongle30 commented
duplicate